# This file was generated by GoReleaser. DO NOT EDIT.
cask "fledge" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "7e2a07f7f9629a59796ecfb7fe8bf185bed9eccc7ed21ab797e5223d5cb91e99"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "290dfffbd2ea3e58a874e29d0285b168f053ea9016c3af97ecd13d9c197daad9"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41d972487fe99a9758ada07236d71dd028a266dac7a625fac6e5d9d65e05ee8a"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02110bc6998053c0cc50a5cb420976b41d751b7981b3a835917e893b609e3bfb"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_amd64.tar.gz"
    end
  end

  name "fledge"
  desc "Release ad hoc iOS builds to your own devices"
  homepage "https://github.com/TheOutdoorProgrammer/fledge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fledge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/fledge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point it at a server and it reads the rest from fledge.yaml:

      export FLEDGE_URL=https://fledge.example
      export FLEDGE_TOKEN=...
      fledge release

    Building needs Xcode. Publishing an already-exported archive does not.
  EOS
end
