# This file was generated by GoReleaser. DO NOT EDIT.
cask "fledge" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "7caeff9cf179586ad793ce7b22d695b416a7f0c8c7db07eee9f0c1173ca3cb2d"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7189c4c589a381a21b724be0d54df938a6e8cc36789b79bf9e3caa0f710bb82"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a9ae867751992335ed12caba84bb2d955dd43b1e616951a9b72f0d61682023a6"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7717030a32926015a982cb4a51327e5ae41ffb8da2aa508e602cdd33c109974"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_amd64.tar.gz"
    end
  end

  name "fledge"
  desc "Release ad hoc iOS builds to your own devices"
  homepage "https://github.com/TheOutdoorProgrammer/fledge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fledge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/fledge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point it at a server and it reads the rest from fledge.yaml:

      export FLEDGE_URL=https://fledge.example
      export FLEDGE_TOKEN=...
      fledge release

    Building needs Xcode. Publishing an already-exported archive does not.
  EOS
end
