# This file was generated by GoReleaser. DO NOT EDIT.
cask "ollie-hooks" do
  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "a9c458798c93cf9f90024314e9083e74a11ccfa0eb1b559f3ac135790e168622"
      url "https://github.com/TheOutdoorProgrammer/ollie-hooks/releases/download/v#{version}/ollie-hooks_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c59d56d715a28564120874f79e97bcb066d6bb4a996f9082d32011d81ca0f3c7"
      url "https://github.com/TheOutdoorProgrammer/ollie-hooks/releases/download/v#{version}/ollie-hooks_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "09a57ada98b779138b236d67dc578958aa9d363bf3f46e52b424cefb4540a477"
      url "https://github.com/TheOutdoorProgrammer/ollie-hooks/releases/download/v#{version}/ollie-hooks_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d80691c7a35cebaa0b9e827edbd1f21883d9e9923e2b72fd30a2f22eba30674"
      url "https://github.com/TheOutdoorProgrammer/ollie-hooks/releases/download/v#{version}/ollie-hooks_linux_amd64.tar.gz"
    end
  end

  name "ollie-hooks"
  desc "A rule engine for Claude Code hooks"
  homepage "https://github.com/TheOutdoorProgrammer/ollie-hooks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ollie-hooks"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ollie-hooks"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Nothing runs until you enable it:

      ollie-hooks wiring        # settings.json entries to add

    Rules that shell out name their own tool when it is missing. The
    Brewfile in the archive installs the full set if you want it.
  EOS
end
