# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.33.20"

  on_macos do
    on_arm do
      sha256 "b7af20da19e87f24eb91e2518c62589ae0536778f3c53597fcbb54cdd4a118bb"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a0389792297e0459988051966885c8bbdf3f8ba729063c0ea999601e8685993"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3aba731a38a64c95c3b3ae83eacc67f713fda0632f1dfe72c816ba8ec5b72f2b"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb066edd01fd1a1c1a0f20a1f2d44339daf8fb7d1718858b7bfb58a5432c6b80"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
