# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.33.19"

  on_macos do
    on_arm do
      sha256 "e38096f342150e6eaacad95bfa03800bc1a2827bd45f912e9a77747e2f6b1254"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03eee94be813ae404d8f1b6af589e89bb27966c7e6280465521d8f47d7d1e5e2"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "08ca8e3c10ebb893d11c2512fa37c553a770a035800394821fbe0a0d25de6e9c"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "39751d0f196e13b18f0310e5603a2176a60677adaa0b768086fa8eca1d24a9e7"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
