# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.33.14"

  on_macos do
    on_arm do
      sha256 "3dffe0bcd1ae59a4d7f0d2ab1f23fa7c662878bb482488576e516629f7f3fd7e"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c54658690412edee927167cf4d9e625d3cb13da0a8e6426065b6f18fb56fe8b"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f9b3ddc90c92235564a8629154cbbb70c9bc84984666e76b530b72ab7d1fe7a4"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ff746aa380e9c4b810666138e8a6daa602e3cccb418abad4d253e135b6610e9"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
