# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "1.1.3"

  on_macos do
    on_arm do
      sha256 "0be725e7231aad8cc42c87d23f9aa71e980725774ca651ddaaaf6d8a9d95fbd3"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc7048eb4ad6202a2bd8adfe22d0a6ad3959fae281f54e2187be07902c1b45b1"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac913cdf4ffc04d7fa01e2bdbf4038ec11b67dabf8deecdb2f59457d6dae0f53"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5affbddfc7dcfc1d7e9f6cfdcfee3d1f72d64200ae6426cc6b3143d86ffb7713"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/NerdsWhoFish/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
