# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "ff6d82550e12f1d3559ccad3fd55b29fd3e6579058ca6c216b1981d8d0eacb98"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03e3f67fcde33b0fee3641cea1bc922a01389e26b64217b3dcc4acb1439c5515"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c82798ffd3d92655e655ccfe00f181d16bdf0115fb2c3baec422f7dc37071ba"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad4ebaddf436671882bf2bff04b2d9651d204f26feafd8a50251a396bd942ce1"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/NerdsWhoFish/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
