# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "c1a5f3526492ad06ab1e534ef280c640cf7089c59f53eb5b00b2825371f5d0b8"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "605a6f90ae538c6868d3b74d2c82eac81c2b6dacbb131163c4a61fc11913ed7a"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf89084cee9e5d8180e24dd38aca927270ece133819ee4b7b2ac027eb5a2e0f5"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c474afca5540b0bd13c3a134590903915e1f581b93fbd3aafc767cc0250f73f"
      url "https://github.com/NerdsWhoFish/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/NerdsWhoFish/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
